# Generated by Django 4.0.4 on 2023-08-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericModel',
        ),
    ]
