# Generated by Django 4.0.4 on 2023-08-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_alter_climate_name_alter_planet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
