# Generated by Django 4.0.4 on 2023-08-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0003_alter_planet_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
